In [1]:
import bar_chart_race as bcr
import pandas as pd
import numpy as np

In [13]:
df = pd.read_csv('./international_students_in_the_us.csv', index_col='Year')

In [14]:
df.head()

,Burundi,Djibouti,Eritrea,Ethiopia,Kenya,Rwanda,Seychelles,Somalia,South Sudan,Sudan,...,Niue,Norfolk Island,Palau,Papua New Guinea,Samoa,Solomon Islands,Tonga,Tuvalu,Vanuatu,Wallis and Futuna
Year,,,,,,,,,,,,,,,,,,,,,
1949/50,0.0,0.0,0.0,37.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1954/55,0.0,0.0,0.0,62.0,19.0,0.0,0.0,2.0,0.0,7.0,...,0.0,0.0,0.0,0.0,5.0,0.0,1.0,0.0,0.0,0.0
1959/60,0.0,0.0,0.0,170.0,156.0,0.0,0.0,11.0,0.0,53.0,...,0.0,0.0,0.0,0.0,9.0,0.0,7.0,0.0,0.0,0.0
1964/65,6.0,0.0,0.0,266.0,774.0,2.0,2.0,102.0,0.0,180.0,...,0.0,0.0,0.0,0.0,38.0,0.0,90.0,0.0,0.0,0.0
1969/70,6.0,0.0,0.0,540.0,492.0,1.0,5.0,80.0,0.0,135.0,...,0.0,0.0,0.0,4.0,76.0,0.0,93.0,0.0,0.0,0.0

In [15]:
print (df.dtypes)

Burundi              float64
Djibouti             float64
Eritrea              float64
Ethiopia             float64
Kenya                float64
                      ...
Solomon Islands      float64
Tonga                float64
Tuvalu               float64
Vanuatu              float64
Wallis and Futuna    float64
Length: 226, dtype: object

In [16]:
# Replace NaN values
df.fillna(0, inplace=True)

In [17]:
# Aggregate the date
df.iloc[:, 0:-1] = df.iloc[:, 0:-1].cumsum()

In [18]:
df.head()

,Burundi,Djibouti,Eritrea,Ethiopia,Kenya,Rwanda,Seychelles,Somalia,South Sudan,Sudan,...,Niue,Norfolk Island,Palau,Papua New Guinea,Samoa,Solomon Islands,Tonga,Tuvalu,Vanuatu,Wallis and Futuna
Year,,,,,,,,,,,,,,,,,,,,,
1949/50,0.0,0.0,0.0,37.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1954/55,0.0,0.0,0.0,99.0,19.0,0.0,0.0,2.0,0.0,7.0,...,0.0,0.0,0.0,0.0,5.0,0.0,1.0,0.0,0.0,0.0
1959/60,0.0,0.0,0.0,269.0,175.0,0.0,0.0,13.0,0.0,60.0,...,0.0,0.0,0.0,0.0,14.0,0.0,8.0,0.0,0.0,0.0
1964/65,6.0,0.0,0.0,535.0,949.0,2.0,2.0,115.0,0.0,240.0,...,0.0,0.0,0.0,0.0,52.0,0.0,98.0,0.0,0.0,0.0
1969/70,12.0,0.0,0.0,1075.0,1441.0,3.0,7.0,195.0,0.0,375.0,...,0.0,0.0,0.0,4.0,128.0,0.0,191.0,0.0,0.0,0.0

In [19]:
bcr.bar_chart_race(df = df, 
                   n_bars = 20, 
                   sort='desc',
                   title='International Students in the USA',
                   filename = 'International Students in the USA.mp4')

C:\Users\jsu\Anaconda3\lib\site-packages\bar_chart_race\_make_chart.py:284: UserWarning: Glyph 127 () missing from current font.
  fig.canvas.print_figure(io.BytesIO())
C:\Users\jsu\Anaconda3\lib\site-packages\bar_chart_race\_make_chart.py:284: UserWarning: Glyph 128 (\x80) missing from current font.
  fig.canvas.print_figure(io.BytesIO())
C:\Users\jsu\Anaconda3\lib\site-packages\bar_chart_race\_make_chart.py:284: UserWarning: Glyph 129 (\x81) missing from current font.
  fig.canvas.print_figure(io.BytesIO())
C:\Users\jsu\Anaconda3\lib\site-packages\bar_chart_race\_make_chart.py:284: UserWarning: Glyph 130 (\x82) missing from current font.
  fig.canvas.print_figure(io.BytesIO())
C:\Users\jsu\Anaconda3\lib\site-packages\bar_chart_race\_make_chart.py:284: UserWarning: Glyph 131 (\x83) missing from current font.
  fig.canvas.print_figure(io.BytesIO())
C:\Users\jsu\Anaconda3\lib\site-packages\bar_chart_race\_make_chart.py:284: UserWarning: Glyph 132 (\x84) missing from current font.
  fig.canvas.print_figure(io.BytesIO())
C:\Users\jsu\Anaconda3\lib\site-packages\bar_chart_race\_make_chart.py:284: UserWarning: Glyph 133 (\x85) missing from current font.
  fig.canvas.print_figure(io.BytesIO())
C:\Users\jsu\Anaconda3\lib\site-packages\bar_chart_race\_make_chart.py:284: UserWarning: Glyph 134 (\x86) missing from current font.
  fig.canvas.print_figure(io.BytesIO())
C:\Users\jsu\Anaconda3\lib\site-packages\bar_chart_race\_make_chart.py:284: UserWarning: Glyph 135 (\x87) missing from current font.
  fig.canvas.print_figure(io.BytesIO())
C:\Users\jsu\Anaconda3\lib\site-packages\bar_chart_race\_make_chart.py:284: UserWarning: Glyph 136 (\x88) missing from current font.
  fig.canvas.print_figure(io.BytesIO())
C:\Users\jsu\Anaconda3\lib\site-packages\bar_chart_race\_make_chart.py:284: UserWarning: Glyph 137 (\x89) missing from current font.
  fig.canvas.print_figure(io.BytesIO())
C:\Users\jsu\Anaconda3\lib\site-packages\bar_chart_race\_make_chart.py:284: UserWarning: Glyph 138 (\x8a) missing from current font.
  fig.canvas.print_figure(io.BytesIO())
C:\Users\jsu\Anaconda3\lib\site-packages\bar_chart_race\_make_chart.py:284: UserWarning: Glyph 139 (\x8b) missing from current font.
  fig.canvas.print_figure(io.BytesIO())
C:\Users\jsu\Anaconda3\lib\site-packages\bar_chart_race\_make_chart.py:284: UserWarning: Glyph 140 (\x8c) missing from current font.
  fig.canvas.print_figure(io.BytesIO())
C:\Users\jsu\Anaconda3\lib\site-packages\bar_chart_race\_make_chart.py:284: UserWarning: Glyph 141 (\x8d) missing from current font.
  fig.canvas.print_figure(io.BytesIO())
C:\Users\jsu\Anaconda3\lib\site-packages\bar_chart_race\_make_chart.py:284: UserWarning: Glyph 142 (\x8e) missing from current font.
  fig.canvas.print_figure(io.BytesIO())
C:\Users\jsu\Anaconda3\lib\site-packages\bar_chart_race\_make_chart.py:284: UserWarning: Glyph 143 (\x8f) missing from current font.
  fig.canvas.print_figure(io.BytesIO())
C:\Users\jsu\Anaconda3\lib\site-packages\bar_chart_race\_make_chart.py:284: UserWarning: Glyph 144 (\x90) missing from current font.
  fig.canvas.print_figure(io.BytesIO())
C:\Users\jsu\Anaconda3\lib\site-packages\bar_chart_race\_make_chart.py:284: UserWarning: Glyph 145 (\x91) missing from current font.
  fig.canvas.print_figure(io.BytesIO())
C:\Users\jsu\Anaconda3\lib\site-packages\bar_chart_race\_make_chart.py:284: UserWarning: Glyph 146 (\x92) missing from current font.
  fig.canvas.print_figure(io.BytesIO())
C:\Users\jsu\Anaconda3\lib\site-packages\bar_chart_race\_make_chart.py:284: UserWarning: Glyph 147 (\x93) missing from current font.
  fig.canvas.print_figure(io.BytesIO())
C:\Users\jsu\Anaconda3\lib\site-packages\bar_chart_race\_make_chart.py:284: UserWarning: Glyph 148 (\x94) missing from current font.
  fig.canvas.print_figure(io.BytesIO())
C:\Users\jsu\Anaconda3\lib\site-packages\bar_chart_race\_make_chart.py:284: UserWarning: Glyph 149 (\x95) missing from current font.
  fig.canvas.print_figure(io.BytesIO())
C:\Users\jsu\Anaconda3\lib\site-packages\bar_chart_race\_make_chart.py:284: UserWarning: Glyph 150 (\x96) missing from current font.
  fig.canvas.print_figure(io.BytesIO())
C:\Users\jsu\Anaconda3\lib\site-packages\bar_chart_race\_make_chart.py:284: UserWarning: Glyph 151 (\x97) missing from current font.
  fig.canvas.print_figure(io.BytesIO())
C:\Users\jsu\Anaconda3\lib\site-packages\bar_chart_race\_make_chart.py:284: UserWarning: Glyph 152 (\x98) missing from current font.
  fig.canvas.print_figure(io.BytesIO())
C:\Users\jsu\Anaconda3\lib\site-packages\bar_chart_race\_make_chart.py:284: UserWarning: Glyph 153 (\x99) missing from current font.
  fig.canvas.print_figure(io.BytesIO())
C:\Users\jsu\Anaconda3\lib\site-packages\bar_chart_race\_make_chart.py:284: UserWarning: Glyph 154 (\x9a) missing from current font.
  fig.canvas.print_figure(io.BytesIO())
C:\Users\jsu\Anaconda3\lib\site-packages\bar_chart_race\_make_chart.py:284: UserWarning: Glyph 155 (\x9b) missing from current font.
  fig.canvas.print_figure(io.BytesIO())
C:\Users\jsu\Anaconda3\lib\site-packages\bar_chart_race\_make_chart.py:284: UserWarning: Glyph 156 (\x9c) missing from current font.
  fig.canvas.print_figure(io.BytesIO())
C:\Users\jsu\Anaconda3\lib\site-packages\bar_chart_race\_make_chart.py:284: UserWarning: Glyph 157 (\x9d) missing from current font.
  fig.canvas.print_figure(io.BytesIO())
C:\Users\jsu\Anaconda3\lib\site-packages\bar_chart_race\_make_chart.py:284: UserWarning: Glyph 158 (\x9e) missing from current font.
  fig.canvas.print_figure(io.BytesIO())
C:\Users\jsu\Anaconda3\lib\site-packages\bar_chart_race\_make_chart.py:284: UserWarning: Glyph 159 (\x9f) missing from current font.
  fig.canvas.print_figure(io.BytesIO())
C:\Users\jsu\Anaconda3\lib\site-packages\bar_chart_race\_make_chart.py:286: UserWarning: FixedFormatter should only be used together with FixedLocator
  ax.set_yticklabels(self.df_values.columns)
C:\Users\jsu\Anaconda3\lib\site-packages\bar_chart_race\_make_chart.py:287: UserWarning: FixedFormatter should only be used together with FixedLocator
  ax.set_xticklabels([max_val] * len(ax.get_xticks()))
C:\Users\jsu\Anaconda3\lib\site-packages\bar_chart_race\_make_chart.py:226: UserWarning: Some of your columns never make an appearance in the animation. To reduce color repetition, set `filter_column_colors` to `True`
  warnings.warn("Some of your columns never make an appearance in the animation. "